#!/bin/bash -e

pdf(){
# PDF Viewer installation

# check if libpdf.so already exists
if [ -f $PDF ]
then
	echo -e "-------------------------------------\n"
	echo -e "Chrome PDF Viewer: already installed.\n"
	echo -e "Update/Overwrite?\n"
	read -p "[Y]es, [N]o: " reinst
	

for letter in "$reinst"; do  
  
if [[ "$letter" == [Yy] ]]; 
then
	continue
	
elif [[ "$letter" == [Nn]* ]]; 
then
	echo -e "Skipped ...\n"
	exit

else 
	echo -e "\n--------------------------------\n"
	echo    "Non existing value: exiting ..."
	echo -e "\n--------------------------------\n"
	exit 1
fi

done
fi

# pdf variables
ARCH="$(uname -m)"

TDIR="/tmp/chromium-taint/"
CDIR="/usr/lib/chromium-browser"
PDF="/tmp/chromium-taint/opt/google/chrome/libpdf.so"

URL32="https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb"
URL64="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" 

A32="/tmp/chromium-taint/google-chrome-stable_current_i386.deb"
A64="/tmp/chromium-taint/google-chrome-stable_current_amd64.deb"


# pdf installation
echo -e "--------------------------------\n"
echo -e "Installing Chrome PDF Viewer ...\n"
echo -e "--------------------------------\n"

if [ $ARCH == x86_64 ] || [ $ARCH == amd64 ];
then

	echo "64 bit ($ARCH)"
	wget -P $TDIR $URL64
	dpkg -x $A64 $TDIR
	sudo cp $PDF $CDIR
	rm -rf $TDIR

	echo -e "-----------------------------\n"
	echo -e "Chrome PDF Viewer: installed.\n"

elif [ $ARCH == i686 ] || [ $ARCH == i386 ];
then
	echo "32 bit ($ARCH)"
	wget -P $TDIR $URL32
	dpkg -x $A32 $TDIR
	sudo cp $PDF $CDIR
	rm -rf $TDIR

	echo -e "-----------------------------\n"
	echo -e "Chrome PDF Viewer: installed.\n"

else
	echo -e "-----------------------------------\n"
	echo -e	"Exiting: Architecture not supported\n"
	echo -e	"-----------------------------------\n"
	exit 1
fi
}

# Pepper Flash Player installation
pepper(){

# check if pepper is already installed
#if dpkg -s "pepperflashplugin-nonfree" 2> /dev/null 1>/dev/null
#then ...

# pepper installation

echo -e "----------------------------------\n"
echo -e "Installing Pepper Flash Player ...\n"
echo -e "----------------------------------\n"

sudo apt-get -y install pepperflashplugin-nonfree

echo -e "-------------------------------\n"
echo -e "Pepper Flash Player: installed.\n"
}

flash(){
if [[ "$(lsb_release -si)" == "Ubuntu" ]]; then
	
	if dpkg -s "flashplugin-installer" | grep "install ok install"  > /dev/null
	then	
		echo -e "\n---------------------------------\n"
		echo -e "Adobe Flash Plugin is installed ..."
		echo -e "Remove to avoid any possible collision between plugins?\n"
		read -p	"[Y]es, [N]o: " pkgrm

		for letter in "$pkgrm"; do
			if [[ "$letter" == [Yy] ]]; then
				sudo apt-get -y remove flashplugin-installer
			fi
		done
		
elif [ "$(lsb_release -si)" == "Debian" ]; then

	if dpkg -s "flashplugin-nonfree" | grep "install ok install"  > /dev/null
	then
		echo -e "\n---------------------------------\n"
		echo -e "Adobe Flash Plugin is installed ..."
		echo -e "Remove to avoid any possible collision between plugins?\n"
		read -p	"[Y]es, [N]o: " pkgrm

		for letter in "$pkgrm"; do
			if [[ "$letter" == [Yy] ]]; then
				sudo apt-get -y remove flashplugin-nonfree
			fi
		done
	fi
fi
fi
}

echo -e "\n------------------ Chromium-taint ------------------\n"
read -p "Choose what to install ...
 
[C]hrome PDF Viewer
[P]epper Flash Player (only Ubuntu >= 14.04/Debian >= Jessie)
[B]oth \"Pepper Flash Player\" and \"Chrome PDF Viewer\"
[A]bout \"Chromium-taint\"
[E]xit
:" action
  
for letter in "$action"; do  
  
if [[ "$letter" == [Cc] ]]; then
	
	pdf
	continue

elif [[ "$letter" == [Pp]* ]]; then

	# detect if adobe is installed
	# and ask if you want to remove it
	pepper
	break

elif [[ "$letter" == [Bb]* ]]; then

	pdf
	pepper

elif [[ "$letter" == [Ee]* ]]; then

	echo -e "\n-------------------------------\n"
	echo    "Ciao!"
	echo -e "\n-------------------------------\n"
	exit

else 
	echo -e "\n--------------------------------\n"
	echo    "Non existing value: exiting ..."
	echo -e "\n--------------------------------\n"
	exit 1

fi

	echo -e "Please restart Chromium.\n"
	echo    "------------------------------\n"
	# exit?
done

echo -e "Run \"chromium-taint\" to see this again"
echo -e "\n--------------------------------------"
